import type { GroceryCategory } from '../types';

// Ordered: more specific phrases before single keywords, so "olive oil" wins over "olive",
// "tomato paste" wins over "tomato", etc. "frozen" is first so it always overrides.
const KEYWORDS: [string, GroceryCategory][] = [
  // ── Frozen ────────────────────────────────────────────────────────────────
  ['frozen', 'Frozen'],

  // ── Meat & Seafood ────────────────────────────────────────────────────────
  ['ground beef', 'Meat & Seafood'],
  ['ground turkey', 'Meat & Seafood'],
  ['ground pork', 'Meat & Seafood'],
  ['ground chicken', 'Meat & Seafood'],
  ['ground lamb', 'Meat & Seafood'],
  ['ground bison', 'Meat & Seafood'],
  ['chicken thigh', 'Meat & Seafood'],
  ['chicken breast', 'Meat & Seafood'],
  ['chicken wing', 'Meat & Seafood'],
  ['chicken drum', 'Meat & Seafood'],
  ['hot dog', 'Meat & Seafood'],
  ['chicken', 'Meat & Seafood'],
  ['beef', 'Meat & Seafood'],
  ['pork', 'Meat & Seafood'],
  ['turkey', 'Meat & Seafood'],
  ['lamb', 'Meat & Seafood'],
  ['salmon', 'Meat & Seafood'],
  ['shrimp', 'Meat & Seafood'],
  ['prawn', 'Meat & Seafood'],
  ['cod', 'Meat & Seafood'],
  ['tilapia', 'Meat & Seafood'],
  ['halibut', 'Meat & Seafood'],
  ['mahi', 'Meat & Seafood'],
  ['snapper', 'Meat & Seafood'],
  ['swordfish', 'Meat & Seafood'],
  ['trout', 'Meat & Seafood'],
  ['catfish', 'Meat & Seafood'],
  ['herring', 'Meat & Seafood'],
  ['crab', 'Meat & Seafood'],
  ['lobster', 'Meat & Seafood'],
  ['scallop', 'Meat & Seafood'],
  ['clam', 'Meat & Seafood'],
  ['mussel', 'Meat & Seafood'],
  ['squid', 'Meat & Seafood'],
  ['calamari', 'Meat & Seafood'],
  ['octopus', 'Meat & Seafood'],
  ['bacon', 'Meat & Seafood'],
  ['pancetta', 'Meat & Seafood'],
  ['prosciutto', 'Meat & Seafood'],
  ['salami', 'Meat & Seafood'],
  ['pepperoni', 'Meat & Seafood'],
  ['chorizo', 'Meat & Seafood'],
  ['bratwurst', 'Meat & Seafood'],
  ['sausage', 'Meat & Seafood'],
  ['ham', 'Meat & Seafood'],
  ['bison', 'Meat & Seafood'],
  ['venison', 'Meat & Seafood'],
  ['duck', 'Meat & Seafood'],
  ['veal', 'Meat & Seafood'],
  ['steak', 'Meat & Seafood'],
  ['sirloin', 'Meat & Seafood'],
  ['ribeye', 'Meat & Seafood'],
  ['brisket', 'Meat & Seafood'],
  ['ribs', 'Meat & Seafood'],
  ['anchovy', 'Meat & Seafood'],
  ['sardine', 'Meat & Seafood'],
  ['lox', 'Meat & Seafood'],
  ['smoked salmon', 'Meat & Seafood'],

  // ── Dairy & Eggs ──────────────────────────────────────────────────────────
  ['cream cheese', 'Dairy & Eggs'],
  ['sour cream', 'Dairy & Eggs'],
  ['heavy cream', 'Dairy & Eggs'],
  ['whipping cream', 'Dairy & Eggs'],
  ['half and half', 'Dairy & Eggs'],
  ['cottage cheese', 'Dairy & Eggs'],
  ['monterey jack', 'Dairy & Eggs'],
  ['oat milk', 'Dairy & Eggs'],
  ['almond milk', 'Dairy & Eggs'],
  ['soy milk', 'Dairy & Eggs'],
  ['cashew milk', 'Dairy & Eggs'],
  ['rice milk', 'Dairy & Eggs'],
  ['swiss cheese', 'Dairy & Eggs'],
  ['egg', 'Dairy & Eggs'],
  ['butter', 'Dairy & Eggs'],
  ['buttermilk', 'Dairy & Eggs'],
  ['milk', 'Dairy & Eggs'],
  ['cheese', 'Dairy & Eggs'],
  ['yogurt', 'Dairy & Eggs'],
  ['cream', 'Dairy & Eggs'],
  ['cheddar', 'Dairy & Eggs'],
  ['mozzarella', 'Dairy & Eggs'],
  ['parmesan', 'Dairy & Eggs'],
  ['parmigiano', 'Dairy & Eggs'],
  ['pecorino', 'Dairy & Eggs'],
  ['feta', 'Dairy & Eggs'],
  ['ricotta', 'Dairy & Eggs'],
  ['brie', 'Dairy & Eggs'],
  ['camembert', 'Dairy & Eggs'],
  ['gouda', 'Dairy & Eggs'],
  ['gruyere', 'Dairy & Eggs'],
  ['kefir', 'Dairy & Eggs'],
  ['ghee', 'Dairy & Eggs'],
  ['mascarpone', 'Dairy & Eggs'],
  ['provolone', 'Dairy & Eggs'],
  ['havarti', 'Dairy & Eggs'],
  ['manchego', 'Dairy & Eggs'],
  ['colby', 'Dairy & Eggs'],
  ['muenster', 'Dairy & Eggs'],
  ['queso', 'Dairy & Eggs'],
  ['whey', 'Dairy & Eggs'],
  ['gelato', 'Dairy & Eggs'],
  ['ice cream', 'Dairy & Eggs'],

  // ── Canned Goods ──────────────────────────────────────────────────────────
  ['tomato paste', 'Canned Goods'],
  ['tomato sauce', 'Canned Goods'],
  ['crushed tomato', 'Canned Goods'],
  ['diced tomato', 'Canned Goods'],
  ['whole tomato', 'Canned Goods'],
  ['stewed tomato', 'Canned Goods'],
  ['chicken broth', 'Canned Goods'],
  ['beef broth', 'Canned Goods'],
  ['vegetable broth', 'Canned Goods'],
  ['chicken stock', 'Canned Goods'],
  ['beef stock', 'Canned Goods'],
  ['bone broth', 'Canned Goods'],
  ['black bean', 'Canned Goods'],
  ['kidney bean', 'Canned Goods'],
  ['pinto bean', 'Canned Goods'],
  ['navy bean', 'Canned Goods'],
  ['white bean', 'Canned Goods'],
  ['great northern', 'Canned Goods'],
  ['refried bean', 'Canned Goods'],
  ['chickpea', 'Canned Goods'],
  ['garbanzo', 'Canned Goods'],
  ['cannellini', 'Canned Goods'],
  ['coconut milk', 'Canned Goods'],
  ['coconut cream', 'Canned Goods'],
  ['pumpkin puree', 'Canned Goods'],
  ['roasted red pepper', 'Canned Goods'],
  ['green chile', 'Canned Goods'],
  ['chipotle', 'Canned Goods'],
  ['jalapeño', 'Canned Goods'],
  ['artichoke heart', 'Canned Goods'],
  ['water chestnut', 'Canned Goods'],
  ['bamboo shoot', 'Canned Goods'],
  ['applesauce', 'Canned Goods'],
  ['canned tuna', 'Canned Goods'],
  ['canned salmon', 'Canned Goods'],
  ['canned corn', 'Canned Goods'],
  ['canned peach', 'Canned Goods'],
  ['canned pear', 'Canned Goods'],
  ['olives', 'Canned Goods'],
  ['broth', 'Canned Goods'],
  ['stock', 'Canned Goods'],
  ['soup', 'Canned Goods'],
  ['chili', 'Canned Goods'],
  ['lentil', 'Canned Goods'],
  ['salsa', 'Canned Goods'],

  // ── Condiments & Sauces ───────────────────────────────────────────────────
  ['olive oil', 'Condiments & Sauces'],
  ['vegetable oil', 'Condiments & Sauces'],
  ['canola oil', 'Condiments & Sauces'],
  ['coconut oil', 'Condiments & Sauces'],
  ['avocado oil', 'Condiments & Sauces'],
  ['sesame oil', 'Condiments & Sauces'],
  ['peanut oil', 'Condiments & Sauces'],
  ['sunflower oil', 'Condiments & Sauces'],
  ['grapeseed oil', 'Condiments & Sauces'],
  ['soy sauce', 'Condiments & Sauces'],
  ['fish sauce', 'Condiments & Sauces'],
  ['hot sauce', 'Condiments & Sauces'],
  ['oyster sauce', 'Condiments & Sauces'],
  ['hoisin sauce', 'Condiments & Sauces'],
  ['worcestershire', 'Condiments & Sauces'],
  ['apple cider vinegar', 'Condiments & Sauces'],
  ['balsamic vinegar', 'Condiments & Sauces'],
  ['red wine vinegar', 'Condiments & Sauces'],
  ['white wine vinegar', 'Condiments & Sauces'],
  ['rice vinegar', 'Condiments & Sauces'],
  ['dijon', 'Condiments & Sauces'],
  ['mayo', 'Condiments & Sauces'],
  ['mayonnaise', 'Condiments & Sauces'],
  ['ketchup', 'Condiments & Sauces'],
  ['mustard', 'Condiments & Sauces'],
  ['ranch', 'Condiments & Sauces'],
  ['bbq sauce', 'Condiments & Sauces'],
  ['teriyaki', 'Condiments & Sauces'],
  ['sriracha', 'Condiments & Sauces'],
  ['tamari', 'Condiments & Sauces'],
  ['tahini', 'Condiments & Sauces'],
  ['hummus', 'Condiments & Sauces'],
  ['pesto', 'Condiments & Sauces'],
  ['marinara', 'Condiments & Sauces'],
  ['pasta sauce', 'Condiments & Sauces'],
  ['hot sauce', 'Condiments & Sauces'],
  ['buffalo sauce', 'Condiments & Sauces'],
  ['harissa', 'Condiments & Sauces'],
  ['gochujang', 'Condiments & Sauces'],
  ['miso', 'Condiments & Sauces'],
  ['maple syrup', 'Condiments & Sauces'],
  ['agave', 'Condiments & Sauces'],
  ['jam', 'Condiments & Sauces'],
  ['jelly', 'Condiments & Sauces'],
  ['honey', 'Condiments & Sauces'],
  ['pickle', 'Condiments & Sauces'],
  ['relish', 'Condiments & Sauces'],
  ['capers', 'Condiments & Sauces'],
  ['vinegar', 'Condiments & Sauces'],
  ['oil', 'Condiments & Sauces'],
  ['sauce', 'Condiments & Sauces'],
  ['dressing', 'Condiments & Sauces'],
  ['spread', 'Condiments & Sauces'],

  // ── Produce ───────────────────────────────────────────────────────────────
  ['sweet potato', 'Produce'],
  ['bell pepper', 'Produce'],
  ['green onion', 'Produce'],
  ['spring onion', 'Produce'],
  ['bok choy', 'Produce'],
  ['brussels sprout', 'Produce'],
  ['snap pea', 'Produce'],
  ['snow pea', 'Produce'],
  ['grape tomato', 'Produce'],
  ['cherry tomato', 'Produce'],
  ['roma tomato', 'Produce'],
  ['apple', 'Produce'],
  ['apricot', 'Produce'],
  ['asparagus', 'Produce'],
  ['avocado', 'Produce'],
  ['banana', 'Produce'],
  ['basil', 'Produce'],
  ['beet', 'Produce'],
  ['blackberry', 'Produce'],
  ['blueberry', 'Produce'],
  ['broccoli', 'Produce'],
  ['cabbage', 'Produce'],
  ['cantaloupe', 'Produce'],
  ['carrot', 'Produce'],
  ['cauliflower', 'Produce'],
  ['celery', 'Produce'],
  ['cherry', 'Produce'],
  ['cilantro', 'Produce'],
  ['clementine', 'Produce'],
  ['corn', 'Produce'],
  ['cucumber', 'Produce'],
  ['date', 'Produce'],
  ['dill', 'Produce'],
  ['edamame', 'Produce'],
  ['eggplant', 'Produce'],
  ['fennel', 'Produce'],
  ['fig', 'Produce'],
  ['garlic', 'Produce'],
  ['ginger', 'Produce'],
  ['grapefruit', 'Produce'],
  ['grapes', 'Produce'],
  ['jalapeño', 'Produce'],
  ['jalapeno', 'Produce'],
  ['kale', 'Produce'],
  ['kiwi', 'Produce'],
  ['leek', 'Produce'],
  ['lemon', 'Produce'],
  ['lettuce', 'Produce'],
  ['lime', 'Produce'],
  ['mango', 'Produce'],
  ['melon', 'Produce'],
  ['mint', 'Produce'],
  ['mushroom', 'Produce'],
  ['nectarine', 'Produce'],
  ['okra', 'Produce'],
  ['onion', 'Produce'],
  ['orange', 'Produce'],
  ['papaya', 'Produce'],
  ['parsley', 'Produce'],
  ['parsnip', 'Produce'],
  ['peach', 'Produce'],
  ['pear', 'Produce'],
  ['peas', 'Produce'],
  ['pepper', 'Produce'],
  ['pineapple', 'Produce'],
  ['plum', 'Produce'],
  ['pomegranate', 'Produce'],
  ['potato', 'Produce'],
  ['pumpkin', 'Produce'],
  ['radicchio', 'Produce'],
  ['radish', 'Produce'],
  ['raspberry', 'Produce'],
  ['rhubarb', 'Produce'],
  ['rosemary', 'Produce'],
  ['rutabaga', 'Produce'],
  ['sage', 'Produce'],
  ['scallion', 'Produce'],
  ['shallot', 'Produce'],
  ['spinach', 'Produce'],
  ['squash', 'Produce'],
  ['strawberry', 'Produce'],
  ['tangerine', 'Produce'],
  ['thyme', 'Produce'],
  ['tomatillo', 'Produce'],
  ['tomato', 'Produce'],
  ['turnip', 'Produce'],
  ['watermelon', 'Produce'],
  ['zucchini', 'Produce'],
  ['arugula', 'Produce'],
  ['chard', 'Produce'],
  ['chive', 'Produce'],
  ['endive', 'Produce'],
  ['escarole', 'Produce'],
  ['herb', 'Produce'],
  ['horseradish', 'Produce'],
  ['plantain', 'Produce'],
  ['watercress', 'Produce'],
  ['microgreen', 'Produce'],
  ['sprout', 'Produce'],

  // ── Pantry / Dry Goods ────────────────────────────────────────────────────
  ['all-purpose flour', 'Pantry / Dry Goods'],
  ['gluten-free flour', 'Pantry / Dry Goods'],
  ['almond flour', 'Pantry / Dry Goods'],
  ['coconut flour', 'Pantry / Dry Goods'],
  ['bread crumb', 'Pantry / Dry Goods'],
  ['panko', 'Pantry / Dry Goods'],
  ['baking powder', 'Pantry / Dry Goods'],
  ['baking soda', 'Pantry / Dry Goods'],
  ['brown sugar', 'Pantry / Dry Goods'],
  ['powdered sugar', 'Pantry / Dry Goods'],
  ['granulated sugar', 'Pantry / Dry Goods'],
  ['peanut butter', 'Pantry / Dry Goods'],
  ['almond butter', 'Pantry / Dry Goods'],
  ['sunflower butter', 'Pantry / Dry Goods'],
  ['vanilla extract', 'Pantry / Dry Goods'],
  ['cocoa powder', 'Pantry / Dry Goods'],
  ['dark chocolate', 'Pantry / Dry Goods'],
  ['chocolate chip', 'Pantry / Dry Goods'],
  ['protein powder', 'Pantry / Dry Goods'],
  ['flour', 'Pantry / Dry Goods'],
  ['sugar', 'Pantry / Dry Goods'],
  ['salt', 'Pantry / Dry Goods'],
  ['pepper', 'Pantry / Dry Goods'],
  ['rice', 'Pantry / Dry Goods'],
  ['pasta', 'Pantry / Dry Goods'],
  ['noodle', 'Pantry / Dry Goods'],
  ['spaghetti', 'Pantry / Dry Goods'],
  ['penne', 'Pantry / Dry Goods'],
  ['fettuccine', 'Pantry / Dry Goods'],
  ['linguine', 'Pantry / Dry Goods'],
  ['orzo', 'Pantry / Dry Goods'],
  ['couscous', 'Pantry / Dry Goods'],
  ['quinoa', 'Pantry / Dry Goods'],
  ['oat', 'Pantry / Dry Goods'],
  ['granola', 'Pantry / Dry Goods'],
  ['cereal', 'Pantry / Dry Goods'],
  ['bread', 'Pantry / Dry Goods'],
  ['tortilla', 'Pantry / Dry Goods'],
  ['cracker', 'Pantry / Dry Goods'],
  ['barley', 'Pantry / Dry Goods'],
  ['bulgur', 'Pantry / Dry Goods'],
  ['buckwheat', 'Pantry / Dry Goods'],
  ['cornmeal', 'Pantry / Dry Goods'],
  ['cornstarch', 'Pantry / Dry Goods'],
  ['arrowroot', 'Pantry / Dry Goods'],
  ['tapioca', 'Pantry / Dry Goods'],
  ['almond', 'Pantry / Dry Goods'],
  ['cashew', 'Pantry / Dry Goods'],
  ['walnut', 'Pantry / Dry Goods'],
  ['pecan', 'Pantry / Dry Goods'],
  ['pistachio', 'Pantry / Dry Goods'],
  ['peanut', 'Pantry / Dry Goods'],
  ['pine nut', 'Pantry / Dry Goods'],
  ['macadamia', 'Pantry / Dry Goods'],
  ['hazelnut', 'Pantry / Dry Goods'],
  ['sesame seed', 'Pantry / Dry Goods'],
  ['chia seed', 'Pantry / Dry Goods'],
  ['flaxseed', 'Pantry / Dry Goods'],
  ['sunflower seed', 'Pantry / Dry Goods'],
  ['pumpkin seed', 'Pantry / Dry Goods'],
  ['hemp seed', 'Pantry / Dry Goods'],
  ['chocolate', 'Pantry / Dry Goods'],
  ['cocoa', 'Pantry / Dry Goods'],
  ['vanilla', 'Pantry / Dry Goods'],
  ['yeast', 'Pantry / Dry Goods'],
  ['coffee', 'Pantry / Dry Goods'],
  ['tea', 'Pantry / Dry Goods'],
  ['raisin', 'Pantry / Dry Goods'],
  ['dried cranberry', 'Pantry / Dry Goods'],
  ['dried apricot', 'Pantry / Dry Goods'],
  ['popcorn', 'Pantry / Dry Goods'],
  ['chips', 'Pantry / Dry Goods'],
  ['pretzel', 'Pantry / Dry Goods'],
  ['spice', 'Pantry / Dry Goods'],
  ['seasoning', 'Pantry / Dry Goods'],
  ['cumin', 'Pantry / Dry Goods'],
  ['paprika', 'Pantry / Dry Goods'],
  ['turmeric', 'Pantry / Dry Goods'],
  ['cinnamon', 'Pantry / Dry Goods'],
  ['oregano', 'Pantry / Dry Goods'],
  ['cayenne', 'Pantry / Dry Goods'],
  ['chili powder', 'Pantry / Dry Goods'],
  ['garlic powder', 'Pantry / Dry Goods'],
  ['onion powder', 'Pantry / Dry Goods'],
  ['Italian seasoning', 'Pantry / Dry Goods'],
  ['bay leaf', 'Pantry / Dry Goods'],
  ['cardamom', 'Pantry / Dry Goods'],
  ['cloves', 'Pantry / Dry Goods'],
  ['coriander', 'Pantry / Dry Goods'],
  ['cumin', 'Pantry / Dry Goods'],
  ['fennel seed', 'Pantry / Dry Goods'],
  ['nutmeg', 'Pantry / Dry Goods'],
  ['allspice', 'Pantry / Dry Goods'],
  ['smoked paprika', 'Pantry / Dry Goods'],
  ['red pepper flake', 'Pantry / Dry Goods'],
  ['dried herb', 'Pantry / Dry Goods'],
];

function significantWords(s: string): Set<string> {
  return new Set(
    s.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(w => w.length > 2)
  );
}

export function categorizeGroceryItem(
  name: string,
  existingGrocery: { name: string; category: string }[],
): GroceryCategory {
  const lower = name.toLowerCase();
  const words = significantWords(name);

  // 1. Match against existing grocery list items by word overlap — inherit their category
  for (const item of existingGrocery) {
    const itemWords = significantWords(item.name);
    for (const w of words) {
      if (itemWords.has(w)) return item.category as GroceryCategory;
    }
  }

  // 2. Dictionary lookup — phrases first (ordered list handles priority)
  for (const [keyword, category] of KEYWORDS) {
    if (lower.includes(keyword)) return category;
  }

  return 'Other';
}
